version: '3.8'

services:
    app:
        build:
            context: docker/php
            dockerfile: Dockerfile
            target: app-dev
            args:
                USER_ID: ${USER_ID:-0}
                GROUP_ID: ${GROUP_ID:-0}
        command: php -S 0.0.0.0:80 -t public
        env_file:
            - .env
        ports:
            - "8080:80"
        volumes:
            - ".:/app"
            - "./docker/volumes/composer-cache:/home/dev/composer"
        depends_on:
            -  database
    database:
        image: mysql:${MYSQL_VERSION}
        ports:
            - "3386:3306"
        env_file:
            - .env
        volumes:
            - "./docker/volumes/mysql:/var/lib/mysql"
            - "./docker/mysql:/docker-entrypoint-initdb.d"